# ===================================================================
# BASE A - PRINCIPAL
# ===================================================================
spring.datasource.url=jdbc:h2:mem:db_principal;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================================================
# BASE B - AUDITORIA
# ===================================================================
audit.datasource.url=jdbc:h2:mem:db_auditoria;DB_CLOSE_DELAY=-1
audit.datasource.driverClassName=org.h2.Driver
audit.datasource.username=sa
audit.datasource.password=

# ===================================================================
# SWAGGER
# ===================================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html